package actions

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100

const PLAYER_ATTACK_MIN_DMG=5
const PLAYER_ATTACK_MAX_DMG=10

const PLAYER_SPECIAL_ATTACK_MIN_DMG=10
const PLAYER_SPECIAL_ATTACK_MAX_DMG=20

const PLAYER_HEAL_MIN=1
const PLAYER_HEAL_MAX=20

const MONSTER_ATTACK_MIN_DMG=1
const MONSTER_ATTACK_MAX_DMG=5

const MONSTER_SPECIAL_ATTACK_MIN_DMG=50
const MONSTER_SPECIAL_ATTACK_MAX_DMG=70

const LOSE_POINT=0